CREATE TABLE objectives (name TEXT,maxScore INTEGER,requirements TEXT,gamemode TEXT);
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Ones','5','y1Zm','classic');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Twos','10','y2Zm','classic');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Threes','15','y3Zm','classic');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Fours','20','y4Zm','classic');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Fives','25','y5Zm','classic');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Sixes','30','y6Zm','classic');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Bonus','50','byZc/50','classic');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('One Pair','12','x2Zm','classic');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Two Pairs','22','x2Zx2Zm','classic');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Three of a Kind','18','x3Zm','classic');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Four of a Kind','24','x4Zm','classic');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Small Straight','15','d5A1Zm','classic');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Large Straight','20','d6A2Zm','classic');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Full House','28','x3Zx2Zm','classic');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Chance','30','r5Zm','classic');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Yatzy','50','x5Zc/50','classic');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Ones','5','y1Zm','maxi');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Twos','10','y2Zm','maxi');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Threes','15','y3Zm','maxi');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Fours','20','y4Zm','maxi');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Fives','25','y5Zm','maxi');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Sixes','30','y6Zm','maxi');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Bonus','50','byZc/100','maxi');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('One Pair','12','x2Zm','maxi');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Two Pairs','22','x2Zx2Zm','maxi');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Three Pairs','30','x2Zx2Zx2Zm','maxi');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Three of a Kind','18','x3Zm','maxi');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Four of a Kind','24','x4Zm','maxi');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Five of a Kind','30','x5Zm','maxi');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Small Straight','15','d5A1Zm','maxi');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Large Straight','20','d6A2Zm','maxi');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Full Straight','21','d6A1Zm','maxi');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Cabin','28','x3Zx2Zm','maxi');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Tower','34','x4Zx2Zm','maxi');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Full House','36','x3Zx3Zm','maxi');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Chance','36','r6Zm','maxi');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Maxi Yatzy','100','x6Zc/100','maxi');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Two Pairs','22','x2Zx2Zm','fast');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Sixes','30','y6Zm','fast');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Chance','30','r5Zm','fast');