CREATE TABLE objectives (name TEXT,maxScore INTEGER,requirements TEXT,gamemode TEXT);
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Ones','5','y1m','classic');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Twos','10','y2m','classic');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Threes','15','y3m','classic');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Fours','20','y4m','classic');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Fives','25','y5m','classic');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Sixes','30','y6m','classic');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Bonus','50','byc/50','classic');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('One Pair','12','2xm','classic');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Two Pairs','22','2x2xm','classic');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Three of a Kind','18','3xm','classic');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Four of a Kind','24','4xm','classic');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Small Straight','15','d51m','classic');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Large Straight','20','d62m','classic');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Full House','28','3x2xm','classic');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Chance','30','5rm','classic');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Yatzy','50','5xc/50','classic');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Ones','5','y1m','maxi');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Twos','10','y2m','maxi');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Threes','15','y3m','maxi');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Fours','20','y4m','maxi');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Fives','25','y5m','maxi');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Sixes','30','y6m','maxi');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Bonus','50','byc/100','maxi');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('One Pair','12','2xm','maxi');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Two Pairs','22','2x2xm','maxi');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Three Pairs','30','2x2x2xm','maxi');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Three of a Kind','18','3xm','maxi');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Four of a Kind','24','4xm','maxi');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Five of a Kind','30','5xm','maxi');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Small Straight','15','d51m','maxi');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Large Straight','20','d62m','maxi');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Full Straight','21','d61m','maxi');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Cabin','28','3x2xm','maxi');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Tower','34','4x2xm','maxi');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Full House','36','3x3xm','maxi');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Chance','36','6rm','maxi');
INSERT INTO objectives (name,maxScore,requirements,gamemode) VALUES ('Maxi Yatzy','100','6xc/100','maxi');